[package]
name = "final_tcp_server"
version = "0.1.0"
authors = ["Your Name <you@example.com"]
edition = "2021"

[dependencies]
futures = "0.3"

[dependencies.async-std]
version = "1.12"
features = ["attributes"]